name: Smoke test

on:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  sign-verify:
    name: Sign/Verify Artifact
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Checkout source
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
    - name: Setup node
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
      with:
        node-version: 16
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Build sigstore-js
      run: |
        npm run build
    - name: Create artifact to sign
      run: |
        echo -n "hello world" > artifact
    - name: Sign artifact
      run: |
        ./bin/sigstore.js attest artifact "text/plain" > bundle.sigstore
    - name: Verify bundle
      run: |
        ./bin/sigstore.js verify bundle.sigstore
    - name: Archive bundle
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
      with:
        name: bundle
        path: bundle.sigstore

